/*

 MONALISA_TILES_COMP.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 252

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __monalisa_tiles_comp_h_INCLUDE
#define __monalisa_tiles_comp_h_INCLUDE

/* Bank of tiles. */
#define monalisa_tiles_compBank 0

/* Super Gameboy palette 0 */
#define monalisa_tiles_compSGBPal0c0 0
#define monalisa_tiles_compSGBPal0c1 0
#define monalisa_tiles_compSGBPal0c2 18432
#define monalisa_tiles_compSGBPal0c3 749

/* Super Gameboy palette 1 */
#define monalisa_tiles_compSGBPal1c0 6076
#define monalisa_tiles_compSGBPal1c1 8935
#define monalisa_tiles_compSGBPal1c2 6596
#define monalisa_tiles_compSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define monalisa_tiles_compSGBPal2c0 6076
#define monalisa_tiles_compSGBPal2c1 8935
#define monalisa_tiles_compSGBPal2c2 6596
#define monalisa_tiles_compSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define monalisa_tiles_compSGBPal3c0 6076
#define monalisa_tiles_compSGBPal3c1 8935
#define monalisa_tiles_compSGBPal3c2 6596
#define monalisa_tiles_compSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define monalisa_tiles_compCGBPal0c0 4228
#define monalisa_tiles_compCGBPal0c1 11627
#define monalisa_tiles_compCGBPal0c2 20083
#define monalisa_tiles_compCGBPal0c3 30653

/* Gameboy Color palette 1 */
#define monalisa_tiles_compCGBPal1c0 6076
#define monalisa_tiles_compCGBPal1c1 8935
#define monalisa_tiles_compCGBPal1c2 6596
#define monalisa_tiles_compCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define monalisa_tiles_compCGBPal2c0 6076
#define monalisa_tiles_compCGBPal2c1 8935
#define monalisa_tiles_compCGBPal2c2 6596
#define monalisa_tiles_compCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define monalisa_tiles_compCGBPal3c0 6076
#define monalisa_tiles_compCGBPal3c1 8935
#define monalisa_tiles_compCGBPal3c2 6596
#define monalisa_tiles_compCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define monalisa_tiles_compCGBPal4c0 6076
#define monalisa_tiles_compCGBPal4c1 8935
#define monalisa_tiles_compCGBPal4c2 6596
#define monalisa_tiles_compCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define monalisa_tiles_compCGBPal5c0 6076
#define monalisa_tiles_compCGBPal5c1 8935
#define monalisa_tiles_compCGBPal5c2 6596
#define monalisa_tiles_compCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define monalisa_tiles_compCGBPal6c0 6076
#define monalisa_tiles_compCGBPal6c1 8935
#define monalisa_tiles_compCGBPal6c2 6596
#define monalisa_tiles_compCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define monalisa_tiles_compCGBPal7c0 6076
#define monalisa_tiles_compCGBPal7c1 8935
#define monalisa_tiles_compCGBPal7c2 6596
#define monalisa_tiles_compCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char monalisa_tiles_comp[];

#endif

/* End of MONALISA_TILES_COMP.H */
