/*

 MONALISA_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : monalisa_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __monalisa_map_h_INCLUDE
#define __monalisa_map_h_INCLUDE

#define monalisa_mapWidth 20
#define monalisa_mapHeight 18
#define monalisa_mapBank 0

#define monalisa_map monalisa_mapPLN0
extern const unsigned char monalisa_mapPLN0[];

#endif

/* End of MONALISA_MAP.H */
