#include <gb/cgb.h>

#define BG_DMG_WHITE RGB(29, 31, 28)
#define BG_DMG_LIGHTGREEN RGB(22, 30, 17)
#define BG_DMG_DARKGREEN RGB(10, 19, 15)
#define BG_DMG_BLACK RGB(4, 5, 10)

#define SPR_DMG_WHITE RGB(29, 31, 28)
#define SPR_DMG_LIGHTGREEN RGB(22, 30, 17)
#define SPR_DMG_DARKGREEN RGB(10, 19, 15)
#define SPR_DMG_BLACK RGB(4, 5, 10)

static const UINT16 custom_bg_pal[] = { 
	BG_DMG_WHITE, BG_DMG_LIGHTGREEN, BG_DMG_DARKGREEN, BG_DMG_BLACK
};
static const UINT16 custom_bg_pal_fade_steps[][4] = {
  { BG_DMG_WHITE, BG_DMG_WHITE, BG_DMG_WHITE, BG_DMG_WHITE }, // 0
  { BG_DMG_WHITE, BG_DMG_WHITE, BG_DMG_WHITE, BG_DMG_WHITE }, // 1
  { BG_DMG_WHITE, BG_DMG_WHITE, BG_DMG_WHITE, BG_DMG_LIGHTGREEN }, // 2
  { BG_DMG_WHITE, BG_DMG_WHITE, BG_DMG_LIGHTGREEN, BG_DMG_DARKGREEN }, // 3
  { BG_DMG_WHITE, BG_DMG_LIGHTGREEN, BG_DMG_DARKGREEN, BG_DMG_DARKGREEN }, // 4
  { BG_DMG_WHITE, BG_DMG_LIGHTGREEN, BG_DMG_DARKGREEN, BG_DMG_BLACK } // 5
};

static const UINT16 custom_spr1_pal[] = {
  SPR_DMG_BLACK, SPR_DMG_WHITE, SPR_DMG_LIGHTGREEN, SPR_DMG_BLACK
}; 
static const UINT16 custom_spr1_pal_fade_steps[][4] = {
  { SPR_DMG_WHITE, SPR_DMG_WHITE, SPR_DMG_WHITE, SPR_DMG_WHITE }, // 0
  { SPR_DMG_WHITE, SPR_DMG_WHITE, SPR_DMG_WHITE, SPR_DMG_WHITE }, // 1
  { SPR_DMG_WHITE, SPR_DMG_WHITE, SPR_DMG_WHITE, SPR_DMG_LIGHTGREEN }, // 2 
  { SPR_DMG_LIGHTGREEN,	SPR_DMG_WHITE, SPR_DMG_LIGHTGREEN, SPR_DMG_DARKGREEN }, // 3
  { SPR_DMG_DARKGREEN, SPR_DMG_WHITE, SPR_DMG_LIGHTGREEN, SPR_DMG_DARKGREEN }, // 4
  { SPR_DMG_BLACK, SPR_DMG_WHITE, SPR_DMG_LIGHTGREEN, SPR_DMG_BLACK } // 5
};
