#include <gb/cgb.h>

#define DMG_WHITE RGB(29, 31, 28)
#define DMG_LIGHTGREEN RGB(22, 30, 17)
#define DMG_DARKGREEN RGB(10, 19, 15)
#define DMG_BLACK RGB(4, 5, 10)

static const UINT16 custom_bg_pal[] = { 
	DMG_WHITE, DMG_LIGHTGREEN, DMG_DARKGREEN, DMG_BLACK
};
static const UINT16 custom_bg_pal_fade_steps[][4] = {
  { DMG_WHITE, DMG_WHITE, DMG_WHITE, DMG_WHITE }, // 0
  { DMG_WHITE, DMG_WHITE, DMG_WHITE, DMG_WHITE }, // 1
  { DMG_WHITE, DMG_WHITE, DMG_WHITE, DMG_LIGHTGREEN }, // 2
  { DMG_WHITE, DMG_WHITE, DMG_LIGHTGREEN, DMG_DARKGREEN }, // 3
  { DMG_WHITE, DMG_LIGHTGREEN, DMG_DARKGREEN, DMG_DARKGREEN }, // 4
  { DMG_WHITE, DMG_LIGHTGREEN, DMG_DARKGREEN, DMG_BLACK } // 5
};

static const UINT16 custom_spr1_pal[] = {
  DMG_BLACK, DMG_WHITE, DMG_LIGHTGREEN, DMG_BLACK
}; 
static const UINT16 custom_spr1_pal_fade_steps[][4] = {
  { DMG_WHITE, DMG_WHITE, DMG_WHITE, DMG_WHITE }, // 0
  { DMG_WHITE, DMG_WHITE, DMG_WHITE, DMG_WHITE }, // 1
  { DMG_WHITE, DMG_WHITE, DMG_WHITE, DMG_LIGHTGREEN }, // 2 
  { DMG_LIGHTGREEN,	DMG_WHITE, DMG_LIGHTGREEN, DMG_DARKGREEN }, // 3
  { DMG_DARKGREEN, DMG_WHITE, DMG_LIGHTGREEN, DMG_DARKGREEN }, // 4
  { DMG_BLACK, DMG_WHITE, DMG_LIGHTGREEN, DMG_BLACK } // 5
};
