#ifndef DATA_PTRS_H
#define DATA_PTRS_H

//------------------------------------------------------------------------------
// <auto-generated>
//     This code will be auto generated by GB Studio and is only present here
//     to supress errors shown during engine development.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the project is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

typedef struct _BANK_PTR {
  unsigned char bank;
  unsigned int offset;
} BANK_PTR;

#define DATA_PTRS_BANK 5
#define START_SCENE_INDEX 0x0002
#define START_SCENE_X 0x07
#define START_SCENE_Y 0x07
#define START_SCENE_DIR_X 1
#define START_SCENE_DIR_Y 0
#define START_PLAYER_SPRITE 9
#define START_PLAYER_MOVE_SPEED 1
#define START_PLAYER_ANIM_SPEED 3
#define FONT_BANK 7
#define FONT_BANK_OFFSET 0
#define FRAME_BANK 7
#define FRAME_BANK_OFFSET 3584
#define CURSOR_BANK 7
#define CURSOR_BANK_OFFSET 3728
#define EMOTES_SPRITE_BANK 7
#define EMOTES_SPRITE_BANK_OFFSET 3744
#define NUM_VARIABLES 15

extern const BANK_PTR tileset_bank_ptrs[];
extern const BANK_PTR background_bank_ptrs[];
extern const BANK_PTR background_attr_bank_ptrs[];
extern const BANK_PTR palette_bank_ptrs[];
extern const BANK_PTR sprite_bank_ptrs[];
extern const BANK_PTR scene_bank_ptrs[];
extern const BANK_PTR collision_bank_ptrs[];
extern const BANK_PTR string_bank_ptrs[];
extern const BANK_PTR avatar_bank_ptrs[];
extern const unsigned char (*bank_data_ptrs[])[];
extern const unsigned char * music_tracks[];
extern const unsigned char music_banks[];
extern unsigned char script_variables[16];
extern const unsigned char * music_8fbb75bd0_Data[];

#endif
