#ifndef _VM_EXCEPTIONS_H_INCLUDE
#define _VM_EXCEPTIONS_H_INCLUDE

#define EXCEPTION_RESET 1
#define EXCEPTION_CHANGE_SCENE 2
#define EXCEPTION_SAVE 3
#define EXCEPTION_LOAD 4
#define EXCEPTION_TERMINATE 5

#endif