import React from "react";
import Modal from "../library/Modal";

export default ({ onClose }) => (
  <Modal onClose={onClose}>
    <h1>Sprites</h1>
    <p>
      Add sprites to your game by adding PNG files to your project's{" "}
      <em>/assets/sprites</em> folder.
    </p>
    <h2>Requirements</h2>
    <p>
      Sprite PNGs must only contain the following four colors: #071821 (Dark),
      #86c06c (Mid), #e0f8cf (Light), #65ff00 (Transparent). Colors that are not
      one of these hex codes will be matched to the nearest hex code.
    </p>
    <p>
      A sprite consists of one or more <strong>16x16px</strong> frames laid out
      horizontally in file (e.g. a sprite with three frames will be{" "}
      <strong>48x16px</strong>)
    </p>
    <h2>Static sprites</h2>
    <p>
      For sprites that only need a single frame (e.g. interactive items such as
      signposts) create your PNG as a <strong>16x16px</strong> image containing
      just the one frame required.
    </p>
    <p>
      <img
        src="../images/help/cat.png"
        style={{ height: 32, imageRendering: "pixelated" }}
      />
    </p>
    <h2>Actor</h2>
    <p>
      To make sprites that can face in four directions turning towards the
      player, create a <strong>48x16px</strong> PNG containing the three frames
      forward facing, upwards facing and right facing. The left facing sprite is
      automatically generated by fliping the right facing sprite horizontally so
      does not need to be created.
    </p>
    <p>
      <img
        src="../images/help/npc001.png"
        style={{ height: 32, imageRendering: "pixelated" }}
      />
    </p>
    <h2>Animated Actor</h2>
    <p>
      To make sprites that have animated movement, or that can be used as a
      player character, create a <strong>96x16px</strong> PNG containing six
      frames, two forward facing, two upwards facing and two right facing
      animation frames.
    </p>
    <p>
      As there are limits to how many sprites frames can be loaded into a single
      scene don't use animated sprites unless you know your NPCs will have
      movement.
    </p>
    <p>
      <img
        src="../images/help/player.png"
        style={{ height: 32, imageRendering: "pixelated" }}
      />
    </p>
  </Modal>
);
