export type MenuListenerFn = (arg: unknown) => void;
export type MenuListenerKey =
  | "new"
  | "open"
  | "project"
  | "save"
  | "saveAs"
  | "checkUpdates"
  | "undo"
  | "redo"
  | "section"
  | "zoom"
  | "reloadAssets"
  | "updateTheme"
  | "updateLocale"
  | "updateShowCollisions"
  | "updateShowConnections"
  | "updateShowNavigator"
  | "updateShowSceneScreenGrid"
  | "updateCheckSpelling"
  | "updateEmulatorMuted"
  | "run"
  | "build"
  | "ejectEngine"
  | "ejectWebTemplate"
  | "exportProjectSrc"
  | "exportProjectData"
  | "pasteInPlace"
  | "selectAll"
  | "preferences"
  | "pluginManager"
  | "globalPlugins"
  | "projectPlugins"
  | "openMusic"
  | "toggleMidiInput"
  | "selectMidiInput";

export type MenuZoomType = "in" | "out" | "reset";
