/*

 DUNGEON_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : dungeon_32x32.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define dungeon_mapWidth 32
#define dungeon_mapHeight 32
#define dungeon_mapBank 0

#define dungeon_map dungeon_mapPLN0
extern const unsigned char dungeon_mapPLN0[];

/* End of DUNGEON_MAP.H */
