export const RELOAD_ASSETS = "RELOAD_ASSETS";

export const ADD_ACTOR = "ADD_ACTOR";
export const MOVE_ACTOR = "MOVE_ACTOR";
export const REMOVE_ACTOR = "REMOVE_ACTOR";
export const REMOVE_ACTOR_AT = "REMOVE_ACTOR_AT";
export const SELECT_ACTOR = "SELECT_ACTOR";
export const EDIT_ACTOR = "EDIT_ACTOR";

export const ADD_TRIGGER = "CREATE_TRIGGER";
export const RESIZE_TRIGGER = "RESIZE_TRIGGER";
export const MOVE_TRIGGER = "MOVE_TRIGGER";
export const REMOVE_TRIGGER = "REMOVE_TRIGGER";
export const REMOVE_TRIGGER_AT = "REMOVE_TRIGGER_AT";
export const EDIT_TRIGGER = "EDIT_TRIGGER";

export const EDIT_CUSTOM_EVENT = "EDIT_CUSTOM_EVENT";
export const REMOVE_CUSTOM_EVENT = "REMOVE_CUSTOM_EVENT";
export const SELECT_CUSTOM_EVENT = "SELECT_CUSTOM_EVENT";

export const EDIT_UI = "EDIT_UI";

export const PASTE_ACTOR = "PASTE_ACTOR";
export const PASTE_TRIGGER = "PASTE_TRIGGER";
export const PASTE_SCENE = "PASTE_SCENE";
export const PASTE_CUSTOM_EVENTS = "PASTE_CUSTOM_EVENTS";

export const SET_ACTOR_PREFAB = "SET_ACTOR_PREFAB";
export const SET_TRIGGER_PREFAB = "SET_TRIGGER_PREFAB";
export const SET_SCENE_PREFAB = "SET_SCENE_PREFAB";
