export const SET_SECTION = "SET_SECTION";
export const SET_NAVIGATION_ID = "SET_NAVIGATION_ID";

export const SPRITE_LOAD_REQUEST = "SPRITE_LOAD_REQUEST";
export const SPRITE_LOAD_SUCCESS = "SPRITE_LOAD_SUCCESS";
export const SPRITE_LOAD_FAILURE = "SPRITE_LOAD_FAILURE";
export const SPRITE_REMOVE = "SPRITE_REMOVE";

export const BACKGROUND_LOAD_REQUEST = "BACKGROUND_LOAD_REQUEST";
export const BACKGROUND_LOAD_SUCCESS = "BACKGROUND_LOAD_SUCCESS";
export const BACKGROUND_LOAD_FAILURE = "BACKGROUND_LOAD_FAILURE";
export const BACKGROUND_REMOVE = "BACKGROUND_REMOVE";

export const MUSIC_LOAD_REQUEST = "MUSIC_LOAD_REQUEST";
export const MUSIC_LOAD_SUCCESS = "MUSIC_LOAD_SUCCESS";
export const MUSIC_LOAD_FAILURE = "MUSIC_LOAD_FAILURE";
export const MUSIC_REMOVE = "MUSIC_REMOVE";

export const RELOAD_ASSETS = "RELOAD_ASSETS";

export const ADD_SCENE = "ADD_SCENE";
export const MOVE_SCENE = "MOVE_SCENE";
export const EDIT_SCENE = "EDIT_SCENE";
export const REMOVE_SCENE = "REMOVE_SCENE";
export const SELECT_SCENE = "SELECT_SCENE";


export const DRAG_DESTINATION_START = "DRAG_DESTINATION_START";
export const DRAG_DESTINATION_STOP = "DRAG_DESTINATION_STOP";

export const SIDEBAR_WORLD_RESIZE = "SIDEBAR_WORLD_RESIZE";
export const SIDEBAR_FILES_RESIZE = "SIDEBAR_FILES_RESIZE";

export const ADD_ACTOR = "ADD_ACTOR";
export const MOVE_ACTOR = "MOVE_ACTOR";
export const REMOVE_ACTOR = "REMOVE_ACTOR";
export const REMOVE_ACTOR_AT = "REMOVE_ACTOR_AT";
export const SELECT_ACTOR = "SELECT_ACTOR";
export const EDIT_ACTOR = "EDIT_ACTOR";

export const ADD_TRIGGER = "CREATE_TRIGGER";
export const RESIZE_TRIGGER = "RESIZE_TRIGGER";
export const MOVE_TRIGGER = "MOVE_TRIGGER";
export const REMOVE_TRIGGER = "REMOVE_TRIGGER";
export const REMOVE_TRIGGER_AT = "REMOVE_TRIGGER_AT";
export const EDIT_TRIGGER = "EDIT_TRIGGER";

export const EDIT_CUSTOM_EVENT = "EDIT_CUSTOM_EVENT";
export const REMOVE_CUSTOM_EVENT = "REMOVE_CUSTOM_EVENT";
export const SELECT_CUSTOM_EVENT = "SELECT_CUSTOM_EVENT";

export const EDIT_PROJECT = "EDIT_PROJECT";

export const BUILD_GAME = "BUILD_GAME";

export const EJECT_ENGINE = "EJECT_ENGINE";

export const EDIT_UI = "EDIT_UI";

export const PASTE_ACTOR = "PASTE_ACTOR";
export const PASTE_TRIGGER = "PASTE_TRIGGER";
export const PASTE_SCENE = "PASTE_SCENE";
export const PASTE_CUSTOM_EVENTS = "PASTE_CUSTOM_EVENTS";

export const SET_ACTOR_PREFAB = "SET_ACTOR_PREFAB";
export const SET_TRIGGER_PREFAB = "SET_TRIGGER_PREFAB";
export const SET_SCENE_PREFAB = "SET_SCENE_PREFAB";
