export const SET_TOOL = "SET_TOOL";
export const SET_SECTION = "SET_SECTION";
export const SET_NAVIGATION_ID = "SET_NAVIGATION_ID";

export const PROJECT_LOAD_REQUEST = "PROJECT_LOAD_REQUEST";
export const PROJECT_LOAD_SUCCESS = "PROJECT_LOAD_SUCCESS";
export const PROJECT_LOAD_FAILURE = "PROJECT_LOAD_FAILURE";

export const SPRITE_LOAD_REQUEST = "SPRITE_LOAD_REQUEST";
export const SPRITE_LOAD_SUCCESS = "SPRITE_LOAD_SUCCESS";
export const SPRITE_LOAD_FAILURE = "SPRITE_LOAD_FAILURE";
export const SPRITE_REMOVE = "SPRITE_REMOVE";

export const BACKGROUND_LOAD_REQUEST = "BACKGROUND_LOAD_REQUEST";
export const BACKGROUND_LOAD_SUCCESS = "BACKGROUND_LOAD_SUCCESS";
export const BACKGROUND_LOAD_FAILURE = "BACKGROUND_LOAD_FAILURE";
export const BACKGROUND_REMOVE = "BACKGROUND_REMOVE";

export const MUSIC_LOAD_REQUEST = "MUSIC_LOAD_REQUEST";
export const MUSIC_LOAD_SUCCESS = "MUSIC_LOAD_SUCCESS";
export const MUSIC_LOAD_FAILURE = "MUSIC_LOAD_FAILURE";
export const MUSIC_REMOVE = "MUSIC_REMOVE";

export const PROJECT_SAVE_REQUEST = "PROJECT_SAVE_REQUEST";
export const PROJECT_SAVE_SUCCESS = "PROJECT_SAVE_SUCCESS";
export const PROJECT_SAVE_FAILURE = "PROJECT_SAVE_FAILURE";

export const WORLD_LOAD_REQUEST = "WORLD_LOAD_REQUEST";
export const WORLD_LOAD_SUCCESS = "WORLD_LOAD_SUCCESS";
export const WORLD_LOAD_FAILURE = "WORLD_LOAD_FAILURE";

export const WORLD_SAVE_REQUEST = "WORLD_SAVE_REQUEST";
export const WORLD_SAVE_SUCCESS = "WORLD_SAVE_SUCCESS";
export const WORLD_SAVE_FAILURE = "WORLD_SAVE_FAILURE";

export const ADD_SCENE = "ADD_SCENE";
export const MOVE_SCENE = "MOVE_SCENE";
export const EDIT_SCENE = "EDIT_SCENE";
export const REMOVE_SCENE = "REMOVE_SCENE";
export const SELECT_SCENE = "SELECT_SCENE";
export const DRAG_SCENE = "DRAG_SCENE";
export const DRAG_SCENE_START = "DRAG_SCENE_START";
export const DRAG_SCENE_STOP = "DRAG_SCENE_STOP";

export const ADD_ACTOR = "ADD_ACTOR";
export const MOVE_ACTOR = "MOVE_ACTOR";
export const REMOVE_ACTOR = "REMOVE_ACTOR";
export const REMOVE_ACTOR_AT = "REMOVE_ACTOR_AT";
export const SELECT_ACTOR = "SELECT_ACTOR";
export const EDIT_ACTOR = "EDIT_ACTOR";
export const SELECT_SCRIPT_EVENT = "SELECT_SCRIPT_EVENT";

export const ADD_TRIGGER = "CREATE_TRIGGER";
export const RESIZE_TRIGGER = "RESIZE_TRIGGER";
export const MOVE_TRIGGER = "MOVE_TRIGGER";
export const REMOVE_TRIGGER = "REMOVE_TRIGGER";
export const REMOVE_TRIGGER_AT = "REMOVE_TRIGGER_AT";
export const EDIT_TRIGGER = "EDIT_TRIGGER";
export const SELECT_TRIGGER = "SELECT_TRIGGER";

export const ADD_COLLISION_TILE = "ADD_COLLISION_TILE";
export const REMOVE_COLLISION_TILE = "REMOVE_COLLISION_TILE";

export const RENAME_FLAG = "RENAME_FLAG";

export const SET_STATUS = "SET_STATUS";

export const SELECT_WORLD = "SELECT_WORLD";
export const EDIT_WORLD = "EDIT_WORLD";

export const EDIT_PROJECT = "EDIT_PROJECT";
export const EDIT_PROJECT_SETTINGS = "EDIT_PROJECT_SETTINGS";
export const EDIT_PLAYER_START_AT = "EDIT_PLAYER_START_AT";

export const ZOOM_IN = "ZOOM_IN";
export const ZOOM_OUT = "ZOOM_OUT";
export const ZOOM_RESET = "ZOOM_RESET";

export const CMD_CLEAR = "CMD_CLEAR";
export const CMD_START = "CMD_START";
export const CMD_STD_OUT = "CMD_STD_OUT";
export const CMD_STD_ERR = "CMD_STD_ERR";
export const CMD_COMPLETE = "CMD_COMPLETE";

export const OPEN_HELP = "OPEN_HELP";
export const OPEN_FOLDER = "OPEN_FOLDER";
export const BUILD_GAME = "BUILD_GAME";

export const PLAY_MUSIC = "PLAY_MUSIC";
export const PAUSE_MUSIC = "PAUSE_MUSIC";

export const EDIT_UI = "EDIT_UI";
