/*

 BAR_M.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\SDK\gb-gb\tmp\bar_c.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues

 This file was generated by GBMB v0.8

*/

#define bar_mWidth 20
#define bar_mHeight 18

extern const unsigned char bar_m[];

/* End of BAR_M.H */
