

// From Pandocs
// Padded to a uniform maximum length so they 
// overwrite each other cleanly when printing

const char * sgb_sfx_names_table_a[] = {
    "Dummy flag, re-trigger  ",
    "Nintendo                ",
    "Game Over               ",
    "Drop                    ",
    "OK A                    ",
    "OK B                    ",
    "Select A                ",
    "Select B                ",
    "Select C                ",
    "Mistake Buzzer          ",
    "Catch Item              ",
    "Gate squeaks 1 time     ",
    "Explosion small         ",
    "Explosion medium        ",
    "Explosion large         ",
    "Attacked A              ",
    "Attacked B              ",
    "Hit (punch) A           ",
    "Hit (punch) B           ",
    "Breath in air           ",
    "Rocket Projectile A     ",
    "Rocket Projectile B     ",
    "Escaping Bubble         ",
    "Jump                    ",
    "Fast Jump               ",
    "Jet (rocket) takeoff    ",
    "Jet (rocket) landing    ",
    "Cup breaking            ",
    "Glass breaking          ",
    "Level UP                ",
    "Insert air              ",
    "Sword swing             ",
    "Water falling           ",
    "Fire                    ",
    "Wall collapsing         ",
    "Cancel                  ",
    "Walking                 ",
    "Blocking strike         ",
    "Picture floats on & off ",
    "Fade in                 ",
    "Fade out                ",
    "Window being opened     ",
    "Window being closed     ",
    "Big Laser               ",
    "Stone gate closes/opens ",
    "Teleportation           ",
    "Lightning               ",
    "Earthquake              ",
    "Small Laser             "};

const char * sgb_sfx_names_table_b[] = {
    "Dummy flag, re-trigger  ",
    "Applause small group    ",
    "Applause medium group   ",
    "Applause large group    ",
    "Wind                    ",
    "Rain                    ",
    "Storm                   ",
    "Storm with wind/thunder ",
    "Lightning               ",
    "Earthquake              ",
    "Avalanche               ",
    "Wave                    ",
    "River                   ",
    "Waterfall               ",
    "Small character running ",
    "Horse running           ",
    "Warning sound           ",
    "Approaching car         ",
    "Jet flying              ",
    "UFO flying              ",
    "Electromagnetic waves   ",
    "Score UP                ",
    "Fire                    ",
    "Camera shutter, formanto",
    "Write, formanto         ",
    "Show up title, formanto "};

