//AUTOGENERATED FILE FROM png2mtspr
#define sprite_TILE_H 16
#define sprite_WIDTH 64
#define sprite_HEIGHT 48
#define sprite_PIVOT_X 32
#define sprite_PIVOT_Y 24

extern const UINT8 sprite_data[896];
extern const metasprite_t* const sprite_metasprites[5];
