/*

 FORE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v1.6

*/


/* Bank of tiles. */
#define foreBank 0

/* Super Gameboy palette 0 */
#define foreSGBPal0c0 0
#define foreSGBPal0c1 0
#define foreSGBPal0c2 0
#define foreSGBPal0c3 18

/* Super Gameboy palette 1 */
#define foreSGBPal1c0 6108
#define foreSGBPal1c1 8935
#define foreSGBPal1c2 6596
#define foreSGBPal1c3 6368

/* Super Gameboy palette 2 */
#define foreSGBPal2c0 6108
#define foreSGBPal2c1 8935
#define foreSGBPal2c2 6596
#define foreSGBPal2c3 6368

/* Super Gameboy palette 3 */
#define foreSGBPal3c0 6108
#define foreSGBPal3c1 8935
#define foreSGBPal3c2 6596
#define foreSGBPal3c3 6368

/* Gameboy Color palette 0 */
#define foreCGBPal0c0 32767
#define foreCGBPal0c1 25368
#define foreCGBPal0c2 19026
#define foreCGBPal0c3 0

/* Gameboy Color palette 1 */
#define foreCGBPal1c0 32344
#define foreCGBPal1c1 31
#define foreCGBPal1c2 0
#define foreCGBPal1c3 32767

/* Gameboy Color palette 2 */
#define foreCGBPal2c0 32344
#define foreCGBPal2c1 31
#define foreCGBPal2c2 25368
#define foreCGBPal2c3 32767

/* Gameboy Color palette 3 */
#define foreCGBPal3c0 32344
#define foreCGBPal3c1 32767
#define foreCGBPal3c2 992
#define foreCGBPal3c3 1023

/* Gameboy Color palette 4 */
#define foreCGBPal4c0 32344
#define foreCGBPal4c1 32767
#define foreCGBPal4c2 31744
#define foreCGBPal4c3 31

/* Gameboy Color palette 5 */
#define foreCGBPal5c0 32344
#define foreCGBPal5c1 31
#define foreCGBPal5c2 0
#define foreCGBPal5c3 31744

/* Gameboy Color palette 6 */
#define foreCGBPal6c0 32767
#define foreCGBPal6c1 25368
#define foreCGBPal6c2 19026
#define foreCGBPal6c3 0

/* Gameboy Color palette 7 */
#define foreCGBPal7c0 32767
#define foreCGBPal7c1 25368
#define foreCGBPal7c2 19026
#define foreCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char foreCGB[];
/* Start of tile array. */
extern unsigned char fore[];

/* End of FORE.H */
