/*

 DUNGEON_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 78

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define dungeon_tilesBank 0

/* Super Gameboy palette 0 */
#define dungeon_tilesSGBPal0c0 0
#define dungeon_tilesSGBPal0c1 0
#define dungeon_tilesSGBPal0c2 22528
#define dungeon_tilesSGBPal0c3 44

/* Super Gameboy palette 1 */
#define dungeon_tilesSGBPal1c0 6076
#define dungeon_tilesSGBPal1c1 8935
#define dungeon_tilesSGBPal1c2 6596
#define dungeon_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define dungeon_tilesSGBPal2c0 6076
#define dungeon_tilesSGBPal2c1 8935
#define dungeon_tilesSGBPal2c2 6596
#define dungeon_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define dungeon_tilesSGBPal3c0 6076
#define dungeon_tilesSGBPal3c1 8935
#define dungeon_tilesSGBPal3c2 6596
#define dungeon_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define dungeon_tilesCGBPal0c0 26620
#define dungeon_tilesCGBPal0c1 14096
#define dungeon_tilesCGBPal0c2 10662
#define dungeon_tilesCGBPal0c3 2112

/* Gameboy Color palette 1 */
#define dungeon_tilesCGBPal1c0 6076
#define dungeon_tilesCGBPal1c1 8935
#define dungeon_tilesCGBPal1c2 6596
#define dungeon_tilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define dungeon_tilesCGBPal2c0 6076
#define dungeon_tilesCGBPal2c1 8935
#define dungeon_tilesCGBPal2c2 6596
#define dungeon_tilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define dungeon_tilesCGBPal3c0 6076
#define dungeon_tilesCGBPal3c1 8935
#define dungeon_tilesCGBPal3c2 6596
#define dungeon_tilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define dungeon_tilesCGBPal4c0 6076
#define dungeon_tilesCGBPal4c1 8935
#define dungeon_tilesCGBPal4c2 6596
#define dungeon_tilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define dungeon_tilesCGBPal5c0 6076
#define dungeon_tilesCGBPal5c1 8935
#define dungeon_tilesCGBPal5c2 6596
#define dungeon_tilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define dungeon_tilesCGBPal6c0 6076
#define dungeon_tilesCGBPal6c1 8935
#define dungeon_tilesCGBPal6c2 6596
#define dungeon_tilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define dungeon_tilesCGBPal7c0 6076
#define dungeon_tilesCGBPal7c1 8935
#define dungeon_tilesCGBPal7c2 6596
#define dungeon_tilesCGBPal7c3 5344
/* Start of tile array. */
extern const const unsigned char dungeon_tiles[];

/* End of DUNGEON_TILES.H */
