.TH _fixed 3 "19 Aug 2000" "gbdk-lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_fixed \- Useful definition for fixed point values. 
.SH SYNOPSIS
.br
.PP
\fC#include <asm/types.h>\fR
.PP
.SS Public Members

.in +1c
.ti -1c
.RI "
struct {"
.br
.ti -1c
.RI "  \fBUBYTE\fR \fBl\fR"
.br
.ti -1c
.RI "  \fBUBYTE\fR \fBh\fR"
.br
.ti -1c
.RI "} \fBb\fR"
.br
.RI ""
.br
.ti -1c
.RI "
\fBUWORD\fR \fBw\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Useful definition for fixed point values.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for gbdk-lib from the source code.