.TH hardware.h 3 "19 Aug 2000" "gbdk-lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hardware.h \- Defines that let the GB's hardware registers be accessed from C. 
.SH SYNOPSIS
.br
.PP
.SH DETAILED DESCRIPTION
.PP 
Defines that let the GB's hardware registers be accessed from C.
.PP
See the Pan doc for what to set them to. 
.SH AUTHOR
.PP 
Generated automatically by Doxygen for gbdk-lib from the source code.