.TH sample.h 3 "19 Aug 2000" "gbdk-lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sample.h \- Playback raw sound sample with length len from start at 8192Hz rate. 
.SH SYNOPSIS
.br
.PP
.SS Functions

.in +1c
.ti -1c
.RI "
void \fBplay_sample\fR (\fBUINT8\fR *start, \fBUINT16\fR len) NONBANKED"
.br
.RI "\fIPlay the given, appropriatly formatted sample.\fR"
.PP

.in -1c
.SH DETAILED DESCRIPTION
.PP 
Playback raw sound sample with length len from start at 8192Hz rate.
.PP
len defines the length of the sample in samples/32 or bytes/16. The format of the data is unsigned 4-bit samples, 2 samples per byte, upper 4-bits played before lower 4 bits.
.PP
Adaption for GBDK by Lars Malmborg. Original code by Jeff Frohwein. 
.SH AUTHOR
.PP 
Generated automatically by Doxygen for gbdk-lib from the source code.