.TH time.h 3 "19 Aug 2000" "gbdk-lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
time.h \- Sort of ANSI compliant time functions. 
.SH SYNOPSIS
.br
.PP
.SS Typedefs

.in +1c
.ti -1c
.RI "
typedef \fBUINT16\fR \fBtime_t\fR"
.br
.in -1c
.SS Functions

.in +1c
.ti -1c
.RI "\fBclock_t\fR \fBclock\fR (void) NONBANKED"
.br
.RI "\fIThe \fBclock\fR() function returns an approximation of processor time used by the program.\fR"
.PP
.in +1c

.ti -1c
.RI "
time_t \fBtime\fR (time_t *t)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Sort of ANSI compliant time functions.
.SH FUNCTION DOCUMENTATION
.PP 
.SS \fBclock_t\fR clock (void)
.PP
The \fBclock\fR() function returns an approximation of processor time used by the program.
.PP
The value returned is the CPU time used so far as a clock_t; to get the number of seconds used, divide by CLOCKS_PER_SEC. 
.SH AUTHOR
.PP 
Generated automatically by Doxygen for gbdk-lib from the source code.