/*

 BAR_C.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 31

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v1.6

*/


/* Bank of tiles. */
#define bar_cBank 0

/* Super Gameboy palette 0 */
#define bar_cSGBPal0c0 0
#define bar_cSGBPal0c1 0
#define bar_cSGBPal0c2 0
#define bar_cSGBPal0c3 0

/* Super Gameboy palette 1 */
#define bar_cSGBPal1c0 25368
#define bar_cSGBPal1c1 0
#define bar_cSGBPal1c2 4104
#define bar_cSGBPal1c3 6

/* Super Gameboy palette 2 */
#define bar_cSGBPal2c0 0
#define bar_cSGBPal2c1 0
#define bar_cSGBPal2c2 4104
#define bar_cSGBPal2c3 6

/* Super Gameboy palette 3 */
#define bar_cSGBPal3c0 0
#define bar_cSGBPal3c1 0
#define bar_cSGBPal3c2 4104
#define bar_cSGBPal3c3 6

/* Gameboy Color palette 0 */
#define bar_cCGBPal0c0 32767
#define bar_cCGBPal0c1 25368
#define bar_cCGBPal0c2 19026
#define bar_cCGBPal0c3 0

/* Gameboy Color palette 1 */
#define bar_cCGBPal1c0 18
#define bar_cCGBPal1c1 24
#define bar_cCGBPal1c2 31
#define bar_cCGBPal1c3 12

/* Gameboy Color palette 2 */
#define bar_cCGBPal2c0 384
#define bar_cCGBPal2c1 576
#define bar_cCGBPal2c2 768
#define bar_cCGBPal2c3 992

/* Gameboy Color palette 3 */
#define bar_cCGBPal3c0 12288
#define bar_cCGBPal3c1 18432
#define bar_cCGBPal3c2 24576
#define bar_cCGBPal3c3 31744

/* Gameboy Color palette 4 */
#define bar_cCGBPal4c0 792
#define bar_cCGBPal4c1 1023
#define bar_cCGBPal4c2 396
#define bar_cCGBPal4c3 594

/* Gameboy Color palette 5 */
#define bar_cCGBPal5c0 24600
#define bar_cCGBPal5c1 31775
#define bar_cCGBPal5c2 12300
#define bar_cCGBPal5c3 18450

/* Gameboy Color palette 6 */
#define bar_cCGBPal6c0 19008
#define bar_cCGBPal6c1 25344
#define bar_cCGBPal6c2 32736
#define bar_cCGBPal6c3 12672

/* Gameboy Color palette 7 */
#define bar_cCGBPal7c0 32767
#define bar_cCGBPal7c1 25368
#define bar_cCGBPal7c2 19026
#define bar_cCGBPal7c3 12684
/* CGBpalette entries. */
extern unsigned char bar_cCGB[];
/* Start of tile array. */
extern unsigned char bar_c[];

/* End of BAR_C.H */
