ifndef PORT
PORT = gbz80
endif

# Maccer rule
%.s: %.ms
	maccer -o $@ $<

ifeq ($(MODEL),small)
NEAR_CALLS = 1
else
NEAR_CALLS = 0
endif

ifeq ($(ASM),rgbds)
CFLAGS += --asm=rgbds
# Override the default rule
%.o: %.s

$(LIB): pre $(OBJ) $(CRT0)
	mkdir -p $(BUILD)
ifneq ($(LIB_APPEND), 1)
	rm -f $(LIB)
endif
	xlib $(LIB) a $(OBJ)
ifdef CRT0
	cp -f $(CRT0) $(BUILD)
endif

pre: set-model
	-astorgb.pl global.s > global.asm

%.o: %.c
	$(CC) $(CFLAGS) -c $<

%.asm: %.s
	astorgb.pl $< > $@

%.o: %.rasm
	rgbasm -o$@ $<

%.o: %.asm
	rgbasm -o$@ $<

else
$(LIB): pre $(OBJ) $(CRT0)
	mkdir -p $(BUILD)
	cp -f $(OBJ) $(BUILD)
ifneq ($(LIB_APPEND), 1)
	ls $(OBJ) > $(LIB)
else
	ls $(OBJ) >> $(LIB)
endif
ifdef CRT0
	cp -f $(CRT0) $(BUILD)
endif

pre: set-model

%.o: %.c
	$(CC) $(CFLAGS) -c $<

endif

clean:
	rm -f $(OBJ) $(CLEANSPEC)

set-model:
	if [ -e global.s ]; then \
	grep -v "^\W\.NEAR_CALLS" global.s > tmp1.txt; \
	echo "	.NEAR_CALLS = $(NEAR_CALLS)" > tmp2.txt; \
	cat tmp2.txt tmp1.txt > global.s; \
	head global.s; fi
