PRJDIR		= ..

OBJECTS         = tinitalk.obj

TARGET          = tinitalk.exe

# Compiling entire program or any subproject
# ------------------------------------------
all: $(TARGET)


# My rules
# --------
$(TARGET): $(OBJECTS)
        bcc32 -e$(TARGET) $(OBJECTS)

!include ..\Bcc.inc

