.TH asm/types.h 3 "19 Aug 2000" "gbdk-lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm/types.h \- Shared types definitions. 
.SH SYNOPSIS
.br
.PP
.SS Compounds

.in +1c
.ti -1c
.RI "union \fB_fixed\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "
typedef \fBINT8\fR \fBBOOLEAN\fR"
.br
.RI "\fITRUE or FALSE.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef \fBINT8\fR \fBBYTE\fR"
.br
.RI "\fISigned 8 bit.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef \fBUINT8\fR \fBUBYTE\fR"
.br
.RI "\fIUnsigned 8 bit.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef \fBINT16\fR \fBWORD\fR"
.br
.RI "\fISigned 16 bit.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef \fBUINT16\fR \fBUWORD\fR"
.br
.RI "\fIUnsigned 16 bit.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef \fBINT32\fR \fBLWORD\fR"
.br
.RI "\fISigned 32 bit.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef \fBUINT32\fR \fBULWORD\fR"
.br
.RI "\fIUnsigned 32 bit.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef \fBINT32\fR \fBDWORD\fR"
.br
.RI "\fISigned 32 bit.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef \fBUINT32\fR \fBUDWORD\fR"
.br
.RI "\fIUnsigned 32 bit.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef union \fB_fixed\fR  \fBfixed\fR"
.br
.RI "\fIUseful definition for fixed point values.\fR"
.PP

.in -1c
.SH DETAILED DESCRIPTION
.PP 
Shared types definitions.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for gbdk-lib from the source code.