.TH console.h 3 "19 Aug 2000" "gbdk-lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
console.h \- Console functions that work like Turbo C's. 
.SH SYNOPSIS
.br
.PP
.SS Functions

.in +1c
.ti -1c
.RI "
void \fBgotoxy\fR (\fBUINT8\fR x, \fBUINT8\fR y)"
.br
.RI "\fIMove the cursor to an absolute position.\fR"
.PP
.in +1c

.ti -1c
.RI "
\fBUINT8\fR \fBposx\fR (void)"
.br
.RI "\fIGet the current X position of the cursor.\fR"
.PP
.in +1c

.ti -1c
.RI "
\fBUINT8\fR \fBposy\fR (void)"
.br
.RI "\fIGet the current Y position of the cursor.\fR"
.PP
.in +1c

.ti -1c
.RI "void \fBsetchar\fR (char c)"
.br
.RI "\fIWrites out a single character at the current cursor position.\fR"
.PP

.in -1c
.SH DETAILED DESCRIPTION
.PP 
Console functions that work like Turbo C's.
.PP
Note that the font is 8x8, making the screen 20x18 characters. 
.SH FUNCTION DOCUMENTATION
.PP 
.SS void setchar (char c)
.PP
Writes out a single character at the current cursor position.
.PP
Does not update the cursor or interpret the character. 
.SH AUTHOR
.PP 
Generated automatically by Doxygen for gbdk-lib from the source code.