.TH ctype.h 3 "19 Aug 2000" "gbdk-lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctype.h \- Character type functions. 
.SH SYNOPSIS
.br
.PP
.SS Functions

.in +1c
.ti -1c
.RI "
\fBBOOLEAN\fR \fBisalpha\fR (char c)"
.br
.ti -1c
.RI "
\fBBOOLEAN\fR \fBisupper\fR (char c)"
.br
.ti -1c
.RI "
\fBBOOLEAN\fR \fBislower\fR (char c)"
.br
.ti -1c
.RI "
\fBBOOLEAN\fR \fBisdigit\fR (char c)"
.br
.ti -1c
.RI "
\fBBOOLEAN\fR \fBisspace\fR (char c)"
.br
.ti -1c
.RI "
char \fBtoupper\fR (char c)"
.br
.ti -1c
.RI "
char \fBtolower\fR (char c)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Character type functions.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for gbdk-lib from the source code.