import { KeyBinding } from "./keyBindings";

export const defaultKeys: KeyBinding[] = [
  // Instrument Code
  {
    code: "Digit0",
    command: "editInstrumentField",
    args: 0,
    when: "instrumentColumnFocus",
  },
  {
    code: "Digit1",
    command: "editInstrumentField",
    args: 1,
    when: "instrumentColumnFocus",
  },
  {
    code: "Digit2",
    command: "editInstrumentField",
    args: 2,
    when: "instrumentColumnFocus",
  },
  {
    code: "Digit3",
    command: "editInstrumentField",
    args: 3,
    when: "instrumentColumnFocus",
  },
  {
    code: "Digit4",
    command: "editInstrumentField",
    args: 4,
    when: "instrumentColumnFocus",
  },
  {
    code: "Digit5",
    command: "editInstrumentField",
    args: 5,
    when: "instrumentColumnFocus",
  },
  {
    code: "Digit6",
    command: "editInstrumentField",
    args: 6,
    when: "instrumentColumnFocus",
  },
  {
    code: "Digit7",
    command: "editInstrumentField",
    args: 7,
    when: "instrumentColumnFocus",
  },
  {
    code: "Digit8",
    command: "editInstrumentField",
    args: 8,
    when: "instrumentColumnFocus",
  },
  {
    code: "Digit9",
    command: "editInstrumentField",
    args: 9,
    when: "instrumentColumnFocus",
  },
  {
    code: "Delete",
    command: "editInstrumentField",
    args: null,
    when: "instrumentColumnFocus",
  },
  {
    code: "Backspace",
    command: "editInstrumentField",
    args: null,
    when: "instrumentColumnFocus",
  },

  // Effect Code
  {
    code: "Digit0",
    command: "editEffectCodeField",
    args: 0,
    when: "effectCodeColumnFocus",
  },
  {
    code: "Digit1",
    command: "editEffectCodeField",
    args: 1,
    when: "effectCodeColumnFocus",
  },
  {
    code: "Digit2",
    command: "editEffectCodeField",
    args: 2,
    when: "effectCodeColumnFocus",
  },
  {
    code: "Digit3",
    command: "editEffectCodeField",
    args: 3,
    when: "effectCodeColumnFocus",
  },
  {
    code: "Digit4",
    command: "editEffectCodeField",
    args: 4,
    when: "effectCodeColumnFocus",
  },
  {
    code: "Digit5",
    command: "editEffectCodeField",
    args: 5,
    when: "effectCodeColumnFocus",
  },
  {
    code: "Digit6",
    command: "editEffectCodeField",
    args: 6,
    when: "effectCodeColumnFocus",
  },
  {
    code: "Digit7",
    command: "editEffectCodeField",
    args: 7,
    when: "effectCodeColumnFocus",
  },
  {
    code: "Digit8",
    command: "editEffectCodeField",
    args: 8,
    when: "effectCodeColumnFocus",
  },
  {
    code: "Digit9",
    command: "editEffectCodeField",
    args: 9,
    when: "effectCodeColumnFocus",
  },
  {
    code: "KeyA",
    command: "editEffectCodeField",
    args: 10,
    when: "effectCodeColumnFocus",
  },
  {
    code: "KeyB",
    command: "editEffectCodeField",
    args: 11,
    when: "effectCodeColumnFocus",
  },
  {
    code: "KeyC",
    command: "editEffectCodeField",
    args: 12,
    when: "effectCodeColumnFocus",
  },
  {
    code: "KeyD",
    command: "editEffectCodeField",
    args: 13,
    when: "effectCodeColumnFocus",
  },
  {
    code: "KeyE",
    command: "editEffectCodeField",
    args: 14,
    when: "effectCodeColumnFocus",
  },
  {
    code: "KeyF",
    command: "editEffectCodeField",
    args: 15,
    when: "effectCodeColumnFocus",
  },
  {
    code: "Delete",
    command: "editEffectCodeField",
    args: null,
    when: "effectCodeColumnFocus",
  },
  {
    code: "Backspace",
    command: "editEffectCodeField",
    args: null,
    when: "effectCodeColumnFocus",
  },
  // Subpattern Offset
  {
    code: "Minus",
    command: "editOffsetField",
    args: "-",
    when: "offsetColumnFocus",
  },
  {
    code: "Equal",
    command: "editOffsetField",
    args: "+",
    when: "offsetColumnFocus",
  },
  {
    code: "Digit0",
    command: "editOffsetField",
    args: 0,
    when: "offsetColumnFocus",
  },
  {
    code: "Digit1",
    command: "editOffsetField",
    args: 1,
    when: "offsetColumnFocus",
  },
  {
    code: "Digit2",
    command: "editOffsetField",
    args: 2,
    when: "offsetColumnFocus",
  },
  {
    code: "Digit3",
    command: "editOffsetField",
    args: 3,
    when: "offsetColumnFocus",
  },
  {
    code: "Digit4",
    command: "editOffsetField",
    args: 4,
    when: "offsetColumnFocus",
  },
  {
    code: "Digit5",
    command: "editOffsetField",
    args: 5,
    when: "offsetColumnFocus",
  },
  {
    code: "Digit6",
    command: "editOffsetField",
    args: 6,
    when: "offsetColumnFocus",
  },
  {
    code: "Digit7",
    command: "editOffsetField",
    args: 7,
    when: "offsetColumnFocus",
  },
  {
    code: "Digit8",
    command: "editOffsetField",
    args: 8,
    when: "offsetColumnFocus",
  },
  {
    code: "Digit9",
    command: "editOffsetField",
    args: 9,
    when: "offsetColumnFocus",
  },
  {
    code: "Delete",
    command: "editOffsetField",
    args: null,
    when: "offsetColumnFocus",
  },
  {
    code: "Backspace",
    command: "editOffsetField",
    args: null,
    when: "offsetColumnFocus",
  },
  // Subpattern Jump
  {
    code: "Digit0",
    command: "editJumpField",
    args: 0,
    when: "jumpColumnFocus",
  },
  {
    code: "Digit1",
    command: "editJumpField",
    args: 1,
    when: "jumpColumnFocus",
  },
  {
    code: "Digit2",
    command: "editJumpField",
    args: 2,
    when: "jumpColumnFocus",
  },
  {
    code: "Digit3",
    command: "editJumpField",
    args: 3,
    when: "jumpColumnFocus",
  },
  {
    code: "Digit4",
    command: "editJumpField",
    args: 4,
    when: "jumpColumnFocus",
  },
  {
    code: "Digit5",
    command: "editJumpField",
    args: 5,
    when: "jumpColumnFocus",
  },
  {
    code: "Digit6",
    command: "editJumpField",
    args: 6,
    when: "jumpColumnFocus",
  },
  {
    code: "Digit7",
    command: "editJumpField",
    args: 7,
    when: "jumpColumnFocus",
  },
  {
    code: "Digit8",
    command: "editJumpField",
    args: 8,
    when: "jumpColumnFocus",
  },
  {
    code: "Digit9",
    command: "editJumpField",
    args: 9,
    when: "jumpColumnFocus",
  },
  {
    code: "Delete",
    command: "editJumpField",
    args: null,
    when: "jumpColumnFocus",
  },
  {
    code: "Backspace",
    command: "editJumpField",
    args: null,
    when: "jumpColumnFocus",
  },
  // Effect Param
  {
    code: "Digit0",
    command: "editEffectParamField",
    args: 0,
    when: "effectParamColumnFocus",
  },
  {
    code: "Digit1",
    command: "editEffectParamField",
    args: 1,
    when: "effectParamColumnFocus",
  },
  {
    code: "Digit2",
    command: "editEffectParamField",
    args: 2,
    when: "effectParamColumnFocus",
  },
  {
    code: "Digit3",
    command: "editEffectParamField",
    args: 3,
    when: "effectParamColumnFocus",
  },
  {
    code: "Digit4",
    command: "editEffectParamField",
    args: 4,
    when: "effectParamColumnFocus",
  },
  {
    code: "Digit5",
    command: "editEffectParamField",
    args: 5,
    when: "effectParamColumnFocus",
  },
  {
    code: "Digit6",
    command: "editEffectParamField",
    args: 6,
    when: "effectParamColumnFocus",
  },
  {
    code: "Digit7",
    command: "editEffectParamField",
    args: 7,
    when: "effectParamColumnFocus",
  },
  {
    code: "Digit8",
    command: "editEffectParamField",
    args: 8,
    when: "effectParamColumnFocus",
  },
  {
    code: "Digit9",
    command: "editEffectParamField",
    args: 9,
    when: "effectParamColumnFocus",
  },
  {
    code: "KeyA",
    command: "editEffectParamField",
    args: 10,
    when: "effectParamColumnFocus",
  },
  {
    code: "KeyB",
    command: "editEffectParamField",
    args: 11,
    when: "effectParamColumnFocus",
  },
  {
    code: "KeyC",
    command: "editEffectParamField",
    args: 12,
    when: "effectParamColumnFocus",
  },
  {
    code: "KeyD",
    command: "editEffectParamField",
    args: 13,
    when: "effectParamColumnFocus",
  },
  {
    code: "KeyE",
    command: "editEffectParamField",
    args: 14,
    when: "effectParamColumnFocus",
  },
  {
    code: "KeyF",
    command: "editEffectParamField",
    args: 15,
    when: "effectParamColumnFocus",
  },
  {
    code: "Delete",
    command: "editEffectParamField",
    args: null,
    when: "effectParamColumnFocus",
  },
  {
    code: "Backspace",
    command: "editEffectParamField",
    args: null,
    when: "effectParamColumnFocus",
  },
];

export const openMPTKeys: KeyBinding[] = [
  {
    code: "KeyQ",
    command: "editNoteField",
    args: 0,
    when: "noteColumnFocus",
  },
  {
    code: "KeyW",
    command: "editNoteField",
    args: 1,
    when: "noteColumnFocus",
  },
  {
    code: "KeyE",
    command: "editNoteField",
    args: 2,
    when: "noteColumnFocus",
  },
  {
    code: "KeyR",
    command: "editNoteField",
    args: 3,
    when: "noteColumnFocus",
  },
  {
    code: "KeyT",
    command: "editNoteField",
    args: 4,
    when: "noteColumnFocus",
  },
  {
    code: "KeyY",
    command: "editNoteField",
    args: 5,
    when: "noteColumnFocus",
  },
  {
    code: "KeyU",
    command: "editNoteField",
    args: 6,
    when: "noteColumnFocus",
  },
  {
    code: "KeyI",
    command: "editNoteField",
    args: 7,
    when: "noteColumnFocus",
  },
  {
    code: "KeyO",
    command: "editNoteField",
    args: 8,
    when: "noteColumnFocus",
  },
  {
    code: "KeyP",
    command: "editNoteField",
    args: 9,
    when: "noteColumnFocus",
  },
  {
    code: "BracketLeft",
    command: "editNoteField",
    args: 10,
    when: "noteColumnFocus",
  },
  {
    code: "BracketRight",
    command: "editNoteField",
    args: 11,
    when: "noteColumnFocus",
  },
  {
    code: "KeyA",
    command: "editNoteField",
    args: 12,
    when: "noteColumnFocus",
  },
  {
    code: "KeyS",
    command: "editNoteField",
    args: 13,
    when: "noteColumnFocus",
  },
  {
    code: "KeyD",
    command: "editNoteField",
    args: 14,
    when: "noteColumnFocus",
  },
  {
    code: "KeyF",
    command: "editNoteField",
    args: 15,
    when: "noteColumnFocus",
  },
  {
    code: "KeyG",
    command: "editNoteField",
    args: 16,
    when: "noteColumnFocus",
  },
  {
    code: "KeyH",
    command: "editNoteField",
    args: 17,
    when: "noteColumnFocus",
  },
  {
    code: "KeyJ",
    command: "editNoteField",
    args: 18,
    when: "noteColumnFocus",
  },
  {
    code: "KeyK",
    command: "editNoteField",
    args: 19,
    when: "noteColumnFocus",
  },
  {
    code: "KeyL",
    command: "editNoteField",
    args: 20,
    when: "noteColumnFocus",
  },
  {
    code: "Semicolon",
    command: "editNoteField",
    args: 21,
    when: "noteColumnFocus",
  },
  {
    code: "Quote",
    command: "editNoteField",
    args: 22,
    when: "noteColumnFocus",
  },
  {
    code: "Backslash",
    command: "editNoteField",
    args: 23,
    when: "noteColumnFocus",
  },
  {
    code: "KeyZ",
    command: "editNoteField",
    args: 24,
    when: "noteColumnFocus",
  },
  {
    code: "KeyX",
    command: "editNoteField",
    args: 25,
    when: "noteColumnFocus",
  },
  {
    code: "KeyC",
    command: "editNoteField",
    args: 26,
    when: "noteColumnFocus",
  },
  {
    code: "KeyV",
    command: "editNoteField",
    args: 27,
    when: "noteColumnFocus",
  },
  {
    code: "KeyB",
    command: "editNoteField",
    args: 28,
    when: "noteColumnFocus",
  },
  {
    code: "KeyN",
    command: "editNoteField",
    args: 29,
    when: "noteColumnFocus",
  },
  {
    code: "KeyM",
    command: "editNoteField",
    args: 30,
    when: "noteColumnFocus",
  },
  {
    code: "Comma",
    command: "editNoteField",
    args: 31,
    when: "noteColumnFocus",
  },
  {
    code: "Period",
    command: "editNoteField",
    args: 32,
    when: "noteColumnFocus",
  },
  {
    code: "Slash",
    command: "editNoteField",
    args: 33,
    when: "noteColumnFocus",
  },
  //if (e.code == "??") editNoteCell(34);
  //if (e.code == "??") editNoteCell(35);
  {
    code: "Delete",
    command: "editNoteField",
    args: null,
    when: "noteColumnFocus",
  },
  {
    code: "Backspace",
    command: "editNoteField",
    args: null,
    when: "noteColumnFocus",
  },
];

export const milkytrackerKeys: KeyBinding[] = [
  {
    code: "KeyQ",
    command: "editNoteField",
    args: 12,
    when: "noteColumnFocus",
  },
  {
    code: "Digit2",
    command: "editNoteField",
    args: 13,
    when: "noteColumnFocus",
  },
  {
    code: "KeyW",
    command: "editNoteField",
    args: 14,
    when: "noteColumnFocus",
  },
  {
    code: "Digit3",
    command: "editNoteField",
    args: 15,
    when: "noteColumnFocus",
  },
  {
    code: "KeyE",
    command: "editNoteField",
    args: 16,
    when: "noteColumnFocus",
  },
  {
    code: "KeyR",
    command: "editNoteField",
    args: 17,
    when: "noteColumnFocus",
  },
  {
    code: "Digit5",
    command: "editNoteField",
    args: 18,
    when: "noteColumnFocus",
  },
  {
    code: "KeyT",
    command: "editNoteField",
    args: 19,
    when: "noteColumnFocus",
  },
  {
    code: "Digit6",
    command: "editNoteField",
    args: 20,
    when: "noteColumnFocus",
  },
  {
    code: "KeyY",
    command: "editNoteField",
    args: 21,
    when: "noteColumnFocus",
  },
  {
    code: "Digit7",
    command: "editNoteField",
    args: 22,
    when: "noteColumnFocus",
  },
  {
    code: "KeyU",
    command: "editNoteField",
    args: 23,
    when: "noteColumnFocus",
  },
  {
    code: "KeyI",
    command: "editNoteField",
    args: 24,
    when: "noteColumnFocus",
  },
  {
    code: "Digit9",
    command: "editNoteField",
    args: 25,
    when: "noteColumnFocus",
  },
  {
    code: "KeyO",
    command: "editNoteField",
    args: 26,
    when: "noteColumnFocus",
  },
  {
    code: "Digit0",
    command: "editNoteField",
    args: 27,
    when: "noteColumnFocus",
  },
  {
    code: "KeyP",
    command: "editNoteField",
    args: 28,
    when: "noteColumnFocus",
  },
  {
    code: "BracketLeft",
    command: "editNoteField",
    args: 29,
    when: "noteColumnFocus",
  },
  {
    code: "Equal",
    command: "editNoteField",
    args: 30,
    when: "noteColumnFocus",
  },
  {
    code: "BracketRight",
    command: "editNoteField",
    args: 31,
    when: "noteColumnFocus",
  },
  {
    code: "KeyZ",
    command: "editNoteField",
    args: 0,
    when: "noteColumnFocus",
  },
  {
    code: "KeyS",
    command: "editNoteField",
    args: 1,
    when: "noteColumnFocus",
  },
  {
    code: "KeyX",
    command: "editNoteField",
    args: 2,
    when: "noteColumnFocus",
  },
  {
    code: "KeyD",
    command: "editNoteField",
    args: 3,
    when: "noteColumnFocus",
  },
  {
    code: "KeyC",
    command: "editNoteField",
    args: 4,
    when: "noteColumnFocus",
  },
  {
    code: "KeyV",
    command: "editNoteField",
    args: 5,
    when: "noteColumnFocus",
  },
  {
    code: "KeyG",
    command: "editNoteField",
    args: 6,
    when: "noteColumnFocus",
  },
  {
    code: "KeyB",
    command: "editNoteField",
    args: 7,
    when: "noteColumnFocus",
  },
  {
    code: "KeyH",
    command: "editNoteField",
    args: 8,
    when: "noteColumnFocus",
  },
  {
    code: "KeyN",
    command: "editNoteField",
    args: 9,
    when: "noteColumnFocus",
  },
  {
    code: "KeyJ",
    command: "editNoteField",
    args: 10,
    when: "noteColumnFocus",
  },
  {
    code: "KeyM",
    command: "editNoteField",
    args: 11,
    when: "noteColumnFocus",
  },
  {
    code: "Comma",
    command: "editNoteField",
    args: 12,
    when: "noteColumnFocus",
  },
  {
    code: "KeyL",
    command: "editNoteField",
    args: 13,
    when: "noteColumnFocus",
  },
  {
    code: "Period",
    command: "editNoteField",
    args: 14,
    when: "noteColumnFocus",
  },
  {
    code: "Semicolon",
    command: "editNoteField",
    args: 15,
    when: "noteColumnFocus",
  },
  {
    code: "Slash",
    command: "editNoteField",
    args: 16,
    when: "noteColumnFocus",
  },
  {
    code: "Delete",
    command: "editNoteField",
    args: null,
    when: "noteColumnFocus",
  },
  {
    code: "Backspace",
    command: "editNoteField",
    args: null,
    when: "noteColumnFocus",
  },
];
