/*
 */

#ifndef SDCCCONF_HEADER
#define SDCCCONF_HEADER


#undef SDCC_VERSION_HI
#undef SDCC_VERSION_LO
#undef SDCC_VERSION_P
#undef SDCC_VERSION_STR

#undef PREFIX
#undef DATADIR
#undef SRCDIR

#undef STANDARD_INCLUDE_DIR
#undef SDCC_INCLUDE_DIR
#undef SDCC_LIB_DIR
#undef STD_LIB
#undef STD_INT_LIB
#undef STD_LONG_LIB
#undef STD_FP_LIB
#undef STD_DS390_LIB
#undef HAVE_SYS_SOCKET_H
#undef HAVE_SYS_ISA_DEFS_H
#undef HAVE_ENDIAN_H
#undef HAVE_MACHINE_ENDIAN_H

#undef HAVE_STRERROR

#undef OPT_DISABLE_MCS51
#undef OPT_DISABLE_GBZ80
#undef OPT_DISABLE_Z80
#undef OPT_DISABLE_AVR
#undef OPT_DISABLE_DS390
#undef OPT_DISABLE_PIC
#undef OPT_DISABLE_I186
#undef OPT_DISABLE_TLCS900H

#undef OPT_ENABLE_LIBGC

#endif

/* End of config.h */
