import { TOOL_SELECT, BRUSH_8PX } from "../consts";

export default {
  tools: {
    selected: TOOL_SELECT,
    prefab: null,
  },
  document: {
    path: "",
    root: "",
    loaded: false,
    saving: false,
    modified: false,
  },
  world: {},
  editor: {
    type: "world",
    worldFocus: false,
    scene: "",
    index: 0,
    zoom: 100,
    zoomSprite: 400,
    zoomImage: 200,
    zoomUI: 200,
    dragging: "",
    sceneDragging: false,
    sceneDragX: 0,
    sceneDragY: 0,
    uiVersion: 0,
    variableVersion: 0,
    searchTerm: "",
    hover: {
      sceneId: "",
      actorId: "",
      x: 0,
      y: 0,
    },
    worldScrollX: 0,
    worldScrollY: 0,
    worldScrollThrottledX: 0,
    worldScrollThrottledY: 0,
    worldViewWidth: 0,
    worldViewHeight: 0,
    selectedPalette: 0,
    selectedBrush: BRUSH_8PX,
    showLayers: true,
  },
  navigation: {
    section: "world",
    status: {},
  },
  music: {
    playing: false,
  },
  console: {
    status: "idle",
    output: [],
    warnings: [],
  },
  clipboard: {
    event: null,
    actor: null,
    trigger: null,
    scene: null,
    last: null,
  },
  entities: {
    entities: {
      actors: {},
      backgrounds: {},
      music: {},
      scenes: {},
      spriteSheets: {},
      triggers: {},
      variables: {},
      customEvents: {},
      palettes: {},
    },
    result: {
      settings: {
        showCollisions: true,
        showConnections: true,
        worldScrollX: 0,
        worldScrollY: 0,
        zoom: 100,
        customColorsWhite: "E8F8E0",
        customColorsLight: "B0F088",
        customColorsDark: "509878",
        customColorsBlack: "202850",
        defaultBackgroundPaletteIds: [
          "default-bg-1",
          "default-bg-2",
          "default-bg-3",
          "default-bg-4",
          "default-bg-5",
          "default-bg-6",
        ],
        defaultSpritePaletteId: "default-sprite",
        defaultUIPaletteId: "default-ui",
      },
      scenes: [],
    },
  },
  settings: {
    worldSidebarWidth: 300,
    filesSidebarWidth: 300,
  },
  error: {
    visible: false,
    message: "",
    filename: "",
    line: 0,
    col: 0,
  },
};
