const ItemTypes = {
  SCRIPT_EVENT: "SCRIPT_EVENT",
  SCRIPT_VALUE: "SCRIPT_VALUE",
  SCENE: "SCENE",
  NOTE: "NOTE",
  WORLD_FOLDER: "WORLD_FOLDER",
  CUSTOM_EVENT_FOLDER: "CUSTOM_EVENT_FOLDER",
  CUSTOM_EVENT: "CUSTOM_EVENT",
  ACTOR_PREFAB_FOLDER: "ACTOR_PREFAB_FOLDER",
  ACTOR_PREFAB: "ACTOR_PREFAB",
  TRIGGER_PREFAB_FOLDER: "TRIGGER_PREFAB_FOLDER",
  TRIGGER_PREFAB: "TRIGGER_PREFAB",
  CONSTANT_FOLDER: "CONSTANT_FOLDER",
  CONSTANT: "CONSTANT",
  PALETTE_FOLDER: "PALETTE_FOLDER",
  PALETTE: "PALETTE",
};

export default ItemTypes;
