/*

 BIGMAP_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 247 x 66
   Tile set      : bigmap_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bigmap_map_h_INCLUDE
#define __bigmap_map_h_INCLUDE

#define bigmap_mapWidth 247
#define bigmap_mapHeight 66
#define bigmap_mapBank 0

#define bigmap_map bigmap_mapPLN0
extern const unsigned char bigmap_mapPLN0[];

#endif

/* End of BIGMAP_MAP.H */
