.TH asm/gbz80/types.h 3 "19 Aug 2000" "gbdk-lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm/gbz80/types.h \- Types definitions for the gb. 
.SH SYNOPSIS
.br
.PP
.SS Typedefs

.in +1c
.ti -1c
.RI "
typedef char \fBINT8\fR"
.br
.RI "\fISigned eight bit.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef unsigned char \fBUINT8\fR"
.br
.RI "\fIUnsigned eight bit.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef int \fBINT16\fR"
.br
.RI "\fISigned sixteen bit.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef unsigned int \fBUINT16\fR"
.br
.RI "\fIUnsigned sixteen bit.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef long \fBINT32\fR"
.br
.RI "\fISigned 32 bit.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef unsigned long \fBUINT32\fR"
.br
.RI "\fIUnsigned 32 bit.\fR"
.PP
.in +1c

.ti -1c
.RI "
typedef int \fBsize_t\fR"
.br
.ti -1c
.RI "typedef \fBUINT16\fR \fBclock_t\fR"
.br
.RI "\fIReturned from clock.\fR"
.PP

.in -1c
.SH DETAILED DESCRIPTION
.PP 
Types definitions for the gb.
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef \fBUINT16\fR clock_t
.PP
Returned from clock.
.PP
\fBSee also: \fR
.in +1c
\fBclock\fR() 
.SH AUTHOR
.PP 
Generated automatically by Doxygen for gbdk-lib from the source code.