.TH gbdk-lib.h 3 "19 Aug 2000" "gbdk-lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gbdk-lib.h \- Settings for the greater library system. 
.SH SYNOPSIS
.br
.PP
.SH DETAILED DESCRIPTION
.PP 
Settings for the greater library system.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for gbdk-lib from the source code.