.TH malloc.h 3 "19 Aug 2000" "gbdk-lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
malloc.h \- Header for a simple implementation of malloc(). 
.SH SYNOPSIS
.br
.PP
.SS Compounds

.in +1c
.ti -1c
.RI "struct \fBsmalloc_hunk\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "
#define \fBMALLOC_FREE\fR"
.br
.RI "\fIThe malloc hunk flags Note: Cound have used a negative size a'la TI.\fR"
.PP
.in +1c

.ti -1c
.RI "#define \fBMALLOC_MAGIC\fR"
.br
.RI "\fIMagic number of a header.\fR"
.PP

.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "
typedef struct smalloc_hunk \fBmmalloc_hunk\fR"
.br
.in -1c
.SS Functions

.in +1c
.ti -1c
.RI "
void \fBmalloc_gc\fR (void) NONBANKED"
.br
.RI "\fIGarbage collect (join free hunks).\fR"
.PP
.in +1c

.ti -1c
.RI "
void \fBdebug\fR ( char *routine, char *msg ) NONBANKED"
.br
.RI "\fIdebug message logger.\fR"
.PP

.in -1c
.SS Variables

.in +1c
.ti -1c
.RI "
struct smalloc_hunk* \fBpmmalloc_hunk\fR"
.br
.ti -1c
.RI "
\fBUBYTE\fR \fBmalloc_heap_start\fR"
.br
.RI "\fIStart of free memory, as defined by the linker.\fR"
.PP
.in +1c

.ti -1c
.RI "
pmmalloc_hunk \fBmalloc_first\fR"
.br
.RI "\fIFirst hunk.\fR"
.PP

.in -1c
.SH DETAILED DESCRIPTION
.PP 
Header for a simple implementation of malloc().
.PP
This library may currently be broken. 
.SH DEFINE DOCUMENTATION
.PP 
.SS #define MALLOC_MAGIC ()
.PP
Magic number of a header.
.PP
Gives us some chance of surviving if the list is corrupted 
.SH AUTHOR
.PP 
Generated automatically by Doxygen for gbdk-lib from the source code.