.TH sgb.h 3 "19 Aug 2000" "gbdk-lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgb.h \- Super Gameboy definitions. 
.SH SYNOPSIS
.br
.PP
.SS Functions

.in +1c
.ti -1c
.RI "
\fBUINT8\fR \fBsgb_check\fR (void)"
.br
.RI "\fIReturn a non-null value if running on Super GameBoy.\fR"
.PP

.in -1c
.SH DETAILED DESCRIPTION
.PP 
Super Gameboy definitions.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for gbdk-lib from the source code.