name: Build GB Studio (Win64)
on:
  workflow_dispatch: # Дозволяє запускати збірку вручну кнопкою

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21 # Версія, яку використовує GB Studio

      - name: Install dependencies
        run: |
          corepack enable
          yarn install
          npm run fetch-deps

      - name: Build Application
        run: npm run make -- --arch x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GB-Studio-Windows-UKR
          path: out/make/**/*.zip
